#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=10,walltime=04:00:00,mem=100gb
#PBS -m a
#PBS -l feature='intel16'


module load powertools

module load ANGSD/0.911

cd ${PBS_O_WORKDIR} || exit

subset=`basename ${subset_list} _pairlist`

mkdir ${subset}_angsd_${dt}



angsd -P 10  -bam ${subset_list} -GL 1 -doCounts 1 -doMaf 1 -doDepth 1 -doQsDist 1 -doGlf 1 -doMajorMinor 1 -doGeno 8 -doPost 1 -minQ 15 -minMapQ 20 -minMaf 0.05 -uniqueOnly 1 -remove_bads 1 -setMaxDepthInd 100 -minInd  ${n80} -out ${subset}_angsd_${dt}/${subset}_angsd
