#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=20,walltime=04:00:00,mem=10gb
#PBS -m a
#PBS -l feature='intel16'



source ~/.bash_profile

module load ANGSD/0.911

cd ${PBS_O_WORKDIR} || exit


subset=`basename ${subset_list} _list`

maxdepth=`expr ${n80} \* 50`

angsd -b ${subset_list} -GL 1 -doMajorMinor 1 -P 20 -minMapQ 30 -minQ 20 -minMaf 0.05 -minInd ${n80} -minIndDepth 3 -setMaxDepth ${maxdepth} -dosnpstat -snp_pval 1e-2  1 -hwe_pva 1e-2 -out ${subset}_MM_angsd

angsd -b ${subset_list} -doCounts -P 20 -minMapQ 30 -minQ 20 -minMaf 0.05 -minInd ${n80} -minIndDepth 3 -setMaxDepth ${maxdepth} -dosnpstat -snp_pval 1e-2  1 -hwe_pva 1e-2 -out ${subset}_Count_angsd

angsd -b ${subset_list} -doDepth -P 20 -minMapQ 30 -minQ 20 -minMaf 0.05 -minInd ${n80} -minIndDepth 3 -setMaxDepth ${maxdepth} -dosnpstat -snp_pval 1e-2  1 -hwe_pva 1e-2 -out ${subset}_Depth_angsd

angsd -b ${subset_list} -doQsDist -P 20 -minMapQ 30 -minQ 20 -minMaf 0.05 -minInd ${n80} -minIndDepth 3 -setMaxDepth ${maxdepth} -dosnpstat -snp_pval 1e-2  1 -hwe_pva 1e-2 -out ${subset}_QS_angsd

angsd -b ${subset_list} -doMaf 2 -P 20 -minMapQ 30 -minQ 20 -minMaf 0.05 -minInd ${n80} -minIndDepth 3 -setMaxDepth ${maxdepth} -dosnpstat -snp_pval 1e-2  1 -hwe_pva 1e-2 -out ${subset}_Maf_angsd
