#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=28,walltime=04:00:00,mem=20gb
#PBS -m a
#PBS -l feature='intel16'



source ~/.bash_profile

module load SAMTools/1.5
module load GATK/3.7.0
module load GNU/4.4.5
module load tabix/0.2.6
module load matplotlib/1.3.1

cd ${PBS_O_WORKDIR} || exit


subset=`basename ${subset_list} _list`

# See bcftools call for variant calling from the output of the samtools mpileup command.
# In versions of samtools <= 0.1.19 calling was done with bcftools view. Users are now
# required to choose between the old samtools calling model (-c/--consensus-caller)
# and the new multiallelic calling model (-m/--multiallelic-caller). The multiallelic
# calling model is recommended for most tasks.


mkdir ${subset}_bcf_${dt}
cd ${subset}_${dt} || exit

samtools merge -b ../${subset_list} -f ${subset}.bam
samtools index ${subset}.bam

java -Xmx20g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T RealignerTargetCreator -R ../${genome} -I ${subset}.bam -o ${subset}.intervals -nt 28
java -Xmx20g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T IndelRealigner -R ../${genome} -I ${subset}.bam -targetIntervals ${subset}.intervals -o ${subset}_realigned.bam


bcftools mpileup -O u -x -q 20 --threads 28 -a FORMAT/AD,FORMAT/ADF,FORMAT/ADR,FORMAT/DP,FORMAT/SP,INFO/AD,INFO/ADF,INFO/ADR -F 0.002 -m=3 -p -f ../${genome} ${subset}_realigned.bam | bcftools call -mO z -v -o ${subset}.raw.vcf.gz --threads 20
#samtools mpileup -u -x -q 20 -O -s -t DP -t SP -t AD -t INFO/AD -t ADF -t INFO/ADF -t ADR -t INFO/ADR -t INFO/DPR -t DV -F -m 3 -p -f ${genome} --bam-list ${subset_list} | bcftools call -mO z -o ${subset}.raw.vcf.gz

#tabix -p vcf ${subset}.raw.vcf.gz
#
##-s, --samples <list>  list of samples for sample stats, "-" to include all samples
#bcftools stats -F ${genome} -s - ${subset}.raw.vcf.gz > ${subset}.raw.vcf.gz.stats
#mkdir ${subset}_plots
#plot-vcfstats -p ${subset}_plots/ ${subset}.raw.vcf.gz.stats
#

# This one is keeping anything where the total number of reads is more than 3, not per individual
# and is dropping everything with more than 10 reads overall (not at all what I meant)
#bcftools view ${subset}.raw.vcf.gz | vcfutils.pl varFilter -Q 20 -d 3 -D 10  > ${subset}.vcfutil.filtered.vcf


# This is filtering based on per individual depths. Much better
bcftools view  -i  'MIN(FMT/DP)>2 & MAX(FMT/DP)<100' --min-ac 1:minor -v snps ${subset}.raw.vcf.gz -O z -o ${subset}.bcf.filtered.vcf.gz --threads 28


#java -Xmx10g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T BaseRecalibrator -R ${genome} -I ${subset}_realigned.bam -o ${subset}_recal.table
#java -Xmx10g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T PrintReads -R ${genome} -I <lane.bam> --BSQR ${trimmedfile}_recal.table -o ${trimmedfile}_q20.final.bam -nt 20
