#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=28,walltime=04:00:00,mem=10gb
#PBS -m a
#PBS -l feature='intel16'



source ~/.bash_profile

module load GATK/3.7.0
module load picardTools/1.89


cd ${PBS_O_WORKDIR} || exit


subset=`basename ${subset_list} _list`

java -Xmx10g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T GenotypeGVCFs -R ${genome} -o ${subset}.gatk.vcf  `cat ${subset_list}` -nt 27


#angsd -bam ${subset_list} -domaf 1 -domajorminor 1 -gl 1 -snp_pval 1e-2  -P 5 -dosnpstat 1 -hwe_pval 1e-2 -out ${subset}_snp_angsd
