#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=28,walltime=04:00:00,mem=20gb
#PBS -m a
#PBS -l feature='intel16'



source ~/.bash_profile

module load GATK/3.7.0
module load picardTools/1.89


cd ${PBS_O_WORKDIR} || exit

subset=`basename ${subset_list} _list`

mkdir ${subset}_gatk_${dt}

java -Xmx20g -cp $GATK -jar $GATK/GenomeAnalysisTK.jar -T GenotypeGVCFs -R ${genome} -o ${subset}.gatk.vcf  `cat ${subset_list}` -nt 27

mv ${subset}.gatk.vcf ${subset}_gatk_${dt}
